### ISSUE TITLE
FR: import rstudio-prefs.json or translate it to an R file

### ISSUE THREAD

**Issue by DanChaltiel** [ddsjoberg/rstudio.prefs#18]
Hi,

Thanks for yet another very useful package 👍 .

I would like to use it to unify my experience across multiple computers (and after upgrading RStudio, which is not always seamless) with the same parameters and keybindings.

However, the starting point for that is my present JSON file, which is not always easy to put here and there.

A nice interface would therefore be a function looking like `import_pref_json(json_path)`. You give it a JSON file and it merges the prefs to the current ones and writes the local file accordingly. 
It could also simply be a `from_json` argument to `use_rstudio_prefs()`.
In the same fashion, `import_bindings_json(json_path)` would be great.

Another alternative would be to translate JSON to R. For instance, it would take a path to a JSON file containing this code:

```json
    "always_save_history ": false,
    "save_workspace": "never",
    "load_workspace": false,
    "rainbow_parentheses ": true,
```

And translate it to this R code (to the console or to an R file): 

```r
rstudio.prefs::use_rstudio_prefs(
  always_save_history = FALSE,
  save_workspace = "never",
  load_workspace = FALSE,
  rainbow_parentheses = TRUE
)
```

This way, you could even save the R code and call it using `devtools::source_gist()`!

**Comment by ddsjoberg** [comment]
Thanks for the post @DanChaltiel ! Making the process easier to get the precise experience you want with RStudio would be great.

A couple of thoughts:
- I am not sure that the JSON file contains _all_ of the preference mods you make in the RStudio GUI.
- So any preferences modified in the GUI I think may be saved somewhere in accessible to us? (It's been a couple of years since looking into this, and it may not be correct.) Were you planning on saving the JSON somewhere before doing a fresh install, for example?
- What I do to make it easy to re-create my preferred experience in RStudio IDE, is to store the prefs list in a function in a package. This is the most recent iteration of this function https://pcctc.github.io/croquet/reference/use_pcctc_rstudio_prefs.html
- FYI usethis has added a similar function in teh current dev version https://github.com/r-lib/usethis/blob/e05947f0e49244d7dcb13105a48e32718eb59db5/NEWS.md?plain=1#L51

If you did save the prefs in a gist, I think something as easy as this would work for you:

```r
my_preferences <-
  use_rstudio_prefs(
    always_save_history = FALSE,
    save_workspace = "never",
    load_workspace = FALSE,
    rainbow_parentheses = TRUE
  )

use_rstudio_prefs(!!!my_preferences)
```

**Comment by DanChaltiel** [comment]
Hi Daniel,

On a fresh RStudio install, I replaced the default `rstudio-prefs.json` with the one from my previous installation and so far all my options seem to have been kept. Same for `rstudio_bindings.json`. So I guess all is working pretty good :-)

However, I had trouble remembering where I should get these files from, so the process took a bit of time (and then I discovered  `rstudio_config_path()`). Wrapping this process in a function would make it seamless.

Making a package would be rather overkill in my case.

Your last piece of code is exactly what I would like to achieve, but translating my 57-line JSON file into this code would be long and tedious, and hard to maintain with future new options. 

Here, I see 2 options:

 * `use_rstudio_prefs(from_json="path/to/my/central/rstudio-prefs.json")` to simply copy the JSON to the right place.
 * `get_rstudio_prefs(from_json="path/to/my/central/rstudio-prefs.json", output_file=NULL)` to generate the code you wrote from a given JSON file. It would either write an R `output_file` if given or to the console if `NULL`.

Also, I'm not sure to understand, why should I call `use_rstudio_prefs()` twice, doesn't it already write the prefs the first time in the getter ([use_rstudio_prefs.R#L66](https://github.com/ddsjoberg/rstudio.prefs/blob/main/R/use_rstudio_prefs.R#L66))?

**Comment by ddsjoberg** [comment]
Ahh, ok, I see. 

You'd like a function to save the a JSON file with all your settings somewhere, and another to apply a saved JSON to a new install (be that either to replace the existing JSON of preferences or update existing prefs with the ones in a new JSON file).

The first step is straight forward enough, I think. Below are some outlines of functions that I think would be a good start.

```r

save_current_prefs_as_json <- function(to, overwrite = TRUE, recursive = FALSE, copy.mode = TRUE) {
  file.copy(
    from = rstudio_config_path("rstudio-prefs.json"), 
    to = to, 
    overwrite = overwrite, 
    recursive = recursive, 
    copy.mode = copy.mode
  )
}

use_prefs_from_json <- function(from, overwrite = TRUE, recursive = FALSE, copy.mode = TRUE) {
  file.copy(
    from = from, 
    to = rstudio_config_path("rstudio-prefs.json"), 
    overwrite = overwrite, 
    recursive = recursive, 
    copy.mode = copy.mode
  )
}

update_prefs_from_json <- function(from) {
  # read saved json prefs
  list_saved_prefs <- jsonlite::fromJSON(from)
  
  # read in current prefs
  list_current_prefs <- jsonlite::fromJSON(rstudio_config_path("rstudio-prefs.json"))
  
  # udpate current prefs with new prefs (THIS WOULD NEED TESTING!)
  list_new_prefs <-
    utils::modifyList(
      list_current_prefs,
      list_saved_prefs
    )
  
  # save out updated prefs
  jsonlite::write_json(
    list_new_prefs,
    path = rstudio_config_path("rstudio-prefs.json"),
    pretty = TRUE,
    auto_unbox = TRUE
  )
}
```


While i think it's a worthwhile feature, I am not really looking to take on more maintenance at this time, unfortunately. I just don't have the bandwidth at the moment. I hope these examples can help~

**Comment by DanChaltiel** [comment]
Thanks for the code :-)

Also, I'm curious, why are you closing the issue if you think this is worthwhile? I see many devs doing this instead of labeling the issue as "TODO when I have time" or something similar, and I wonder why.

(PS: I'll do the PR as soon as I get some time to clone the whole repo, this was only a quick online GitHub edit)

**Comment by ddsjoberg** [comment]
The maintenance of a codebase is more work than writing the code. This package is pretty stable at the moment, and unfortunately, I can't take on more maintenance.

I'd be happy to assist to the extent I am able to if you'd like to take these JSON-based functions and write a new package.
